# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: Markdown2Html@3
  inputs:
    mode: 'singleFile'
    markdownPath: '$(Build.SourcesDirectory)\README.md'
    htmlPath: '$(Build.SourcesDirectory)\Blazor.WeatherWidget.App\wwwroot\readme.html'

- task: FileTransform@1
  inputs:
    folderPath: '$(Build.SourcesDirectory)/'
    fileType: 'json'
    targetFiles: '**/appsettings.*.json'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/'



- task: AzureRmWebAppDeployment@4
  displayName: Azure Push
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(4bb05423-80e3-404d-86f3-59bcbc47a7e7)'
    appType: 'webAppLinux'
    WebAppName: 'Blazor-WeatherWidget'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    AppSettings: '-WeatherWidgetSettings.OpenWeatherApiKey $(OpenWeatherMap_APIKey) -WEBSITE_TIME_ZONE "Eastern Standard Time"'
