name: Test-Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: linux-latest

    steps:
      - uses: actions/checkout@v3
          
      - name: setup-dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: dotnet-build (component sln)
        run: dotnet build ./Blazor.WeatherWidget.sln
         
      - name: dotnet-build (app sln)
        run: dotnet build ./Blazor.WeatherWidget.App.sln
        
      - name: build-pack (component csproj)
        run: dotnet pack ./Blazor.WeatherWidget/Blazor.WeatherWidget.csproj
          
